### ISSUE TITLE
Users can apply to be assigned moderator status

### ISSUE THREAD

**Issue by I-Dream-Of-Machines** [Lior-za/Soen341UC3#22]

**Comment by Lior-za** [comment]
Tasks:

- [ ]Add a GUI checkbox in a users profile to request moderator status
- [ ]Write a code the records all the users that have checked marked the request checkbox in the database.
- [ ]Write a code that send an email to Soen341Projectuc3@gmail.com with the users username and email. 
- [ ] Test

**Comment by I-Dream-Of-Machines** [comment]
Is outside the scope of this project.
