### ISSUE TITLE
Users with moderator status can delete questions and answers of other users

### ISSUE THREAD

**Issue by I-Dream-Of-Machines** [Lior-za/Soen341UC3#23]

**Comment by Lior-za** [comment]
Tasks: 

- [ ] Verify if the user has the status of a moderator status in the users database
- [ ] Add GUI 'delete' button to all questions and answers
- [ ] Remove the deleted Question/answer from the database. 
- [ ] Test.

**Comment by I-Dream-Of-Machines** [comment]
Is perhaps outside the scope of this project!
